/* riron-data.js — 電験3種 理論Wiki WIKI_DATA */
window.WIKI_DATA = {
  chapters: [
    {
      id: "ch1",
      num: "01",
      title: "電磁気",
      pages: [
        { id: "coulomb-field",         num: "1.1", title: "静電気・クーロンの法則", freq: "high" },
        { id: "capacitor",             num: "1.2", title: "コンデンサ",             freq: "max", featured: true },
        { id: "electromagnetic-force", num: "1.3", title: "電磁力",                 freq: "high" },
        { id: "magnetic-circuit",      num: "1.4", title: "磁気回路",               freq: "mid" },
      ],
    },
    {
      id: "ch2",
      num: "02",
      title: "電気回路",
      pages: [
        { id: "dc-circuit",    num: "2.1", title: "直流回路",      freq: "max", featured: true },
        { id: "ac-basics",     num: "2.2", title: "交流の基礎",    freq: "max", featured: true },
        { id: "ac-power",      num: "2.3", title: "交流電力",      freq: "high" },
        { id: "rlc-resonance", num: "2.4", title: "RLC回路・共振", freq: "high", featured: true },
        { id: "bridge-circuit",num: "2.5", title: "ブリッジ回路",  freq: "mid" },
      ],
    },
    {
      id: "ch3",
      num: "03",
      title: "電磁誘導・過渡",
      pages: [
        { id: "inductance", num: "3.1", title: "インダクタンス・電磁誘導", freq: "high" },
        { id: "transient",  num: "3.2", title: "過渡現象",                 freq: "high" },
      ],
    },
    {
      id: "ch4",
      num: "04",
      title: "三相交流",
      pages: [
        { id: "three-phase", num: "4.1", title: "三相交流", freq: "max", featured: true },
      ],
    },
    {
      id: "ch5",
      num: "05",
      title: "電子理論",
      pages: [
        { id: "semiconductor", num: "5.1", title: "半導体・ダイオード",  freq: "mid" },
        { id: "transistor",    num: "5.2", title: "トランジスタ",         freq: "high", featured: true },
        { id: "op-amp",        num: "5.3", title: "演算増幅器",           freq: "high", featured: true },
      ],
    },
    {
      id: "ch6",
      num: "06",
      title: "計測",
      pages: [
        { id: "measurement", num: "6.1", title: "電気・電子計測", freq: "mid" },
      ],
    },
    {
      id: "ch7",
      num: "07",
      title: "攻略",
      pages: [
        { id: "trap-patterns",   num: "7.1", title: "引っかけパターン集（37個）", freq: null, featured: true },
        { id: "last-3days",      num: "7.2", title: "直前3日戦略",                freq: null },
        { id: "retake-strategy", num: "7.3", title: "再受験分析と戦略",           freq: null },
      ],
    },
    {
      id: "ref",
      num: "—",
      title: "リファレンス",
      pages: [
        { id: "trends",          num: "A", title: "出題傾向データ", freq: null },
        { id: "glossary",        num: "B", title: "用語集・索引",   freq: null },
        { id: "guide",           num: "C", title: "学習ガイド",     freq: null },
        { id: "formulas",        num: "D", title: "公式集",         freq: null },
        { id: "circuit-patterns",num: "E", title: "回路パターン集", freq: null },
      ],
    },
  ],

  // 出題傾向（過去10年の出題分布、概算値）
  freqData: [
    { topic: "交流回路（インピーダンス・電力）", pct: 17, count: 30 },
    { topic: "三相交流",                       pct: 11, count: 20 },
    { topic: "コンデンサ・静電気",              pct: 11, count: 20 },
    { topic: "電磁誘導・インダクタンス",        pct: 10, count: 18 },
    { topic: "直流回路",                       pct: 10, count: 18 },
    { topic: "RLC共振",                        pct:  8, count: 14 },
    { topic: "電子（BJT/FET/Op-Amp）",         pct: 14, count: 25 },
    { topic: "過渡現象",                       pct:  6, count: 11 },
    { topic: "計測",                           pct:  8, count: 14 },
    { topic: "電磁力・磁気回路",                pct:  5, count: 10 },
  ],

  // 用語集（五十音順）
  glossary: [
    // ア行
    { term: "アドミタンス", reading: "ADMITTANCE", letter: "あ",
      def: "インピーダンスの逆数。Y = 1/Z [S（ジーメンス）]。並列回路では足し算できる。コンダクタンス G とサセプタンス B に分解できる（Y = G + jB）。" },
    { term: "インダクタンス", reading: "INDUCTANCE", letter: "あ",
      def: "コイルが電流変化に対して逆起電力を発生させる係数。v = L·di/dt [H（ヘンリー）]。コイルの形状・巻数・透磁率で決まる。" },
    { term: "インピーダンス", reading: "IMPEDANCE", letter: "あ",
      def: "交流回路における電流の流れにくさ。直流の抵抗に相当するが位相情報も持つ複素量。Z = R + jX [Ω]。" },
    { term: "位相", reading: "PHASE", letter: "あ",
      def: "波の時間的なズレを角度（ラジアンまたは度）で表したもの。電圧と電流の位相差が力率を決める。" },
    { term: "渦電流", reading: "EDDY CURRENT", letter: "あ",
      def: "変化する磁束によって導体内部に誘導される循環電流。鉄心損失の一因であり、薄い鉄板を積層することで低減できる。" },
    { term: "ELIのICEman", reading: "ELI THE ICEMAN", letter: "あ",
      def: "コイル/コンデンサの位相関係を覚える語呂。L（コイル）はE→I（電流が遅れる）、C（コンデンサ）はI→E（電流が進む）。" },
    { term: "IGBT", reading: "IGBT", letter: "あ",
      def: "絶縁ゲートバイポーラトランジスタ。電圧駆動（FET型ゲート）と低オン電圧（バイポーラ型主回路）を両立。中容量インバータの主役。" },
    { term: "アンペアの法則", reading: "AMPERE LAW", letter: "あ",
      def: "閉曲線に沿った磁界の線積分は、その閉曲線で囲まれた電流の総和に等しい。∮H·dl = NI。磁気回路の起磁力計算の基礎。" },

    // カ行
    { term: "角周波数", reading: "ANGULAR FREQUENCY", letter: "か",
      def: "1秒間に何ラジアン進むかを表す量。ω = 2πf [rad/s]。リアクタンス XL = ωL、XC = 1/(ωC)の基本定数。50Hzではω≈314 rad/s。" },
    { term: "共役複素数", reading: "COMPLEX CONJUGATE", letter: "か",
      def: "複素数 Z = a + jb に対して Z* = a − jb。複素電力 S = V·I* で実部が有効電力 P、虚部が無効電力 Q を与える。" },
    { term: "起磁力", reading: "MAGNETOMOTIVE FORCE", letter: "か",
      def: "磁束を発生させる原動力。F = NI [A]。電気回路の起電力に対応する磁気回路の概念。" },
    { term: "虚数単位", reading: "IMAGINARY UNIT", letter: "か",
      def: "j = √(−1)。電気では電流iと区別するためjを使う。フェーザーや複素インピーダンス Z = R + jX を表現する基本。微分d/dtは周波数領域でjωに対応。" },
    { term: "Q値", reading: "QUALITY FACTOR", letter: "か",
      def: "直列RLC共振では Q = ωL/R = 1/(ωCR) の無次元数。Qが大きいほど共振ピークが細く高い。共振時LCの電圧は入力電圧のQ倍に達する。" },
    { term: "共振", reading: "RESONANCE", letter: "か",
      def: "XL = XC となる状態。直列共振では電流最大・インピーダンス最小、並列共振では電流最小・インピーダンス最大。" },
    { term: "クーロン", reading: "COULOMB", letter: "か",
      def: "電荷のSI単位。1 C は約 6.24×10¹⁸ 個の電子が持つ電荷量に相当する。" },
    { term: "クーロンの法則", reading: "COULOMB LAW", letter: "か",
      def: "2つの点電荷間に働く静電気力 F = kQ₁Q₂/r²。r²に反比例する逆二乗則。比例定数 k = 1/(4πε)。" },
    { term: "結合係数", reading: "COUPLING COEFFICIENT", letter: "か",
      def: "相互インダクタンスの大きさを表す無次元数。k = M/√(L₁L₂)、0 ≤ k ≤ 1。k=1が完全結合。" },
    { term: "コンダクタンス", reading: "CONDUCTANCE", letter: "か",
      def: "抵抗の逆数。G = 1/R [S（ジーメンス）]。並列接続時に足し算できる。" },
    { term: "コンデンサ", reading: "CAPACITOR", letter: "か",
      def: "電荷を蓄える素子。Q = CV、エネルギー W = CV²/2。直流定常では開放、t=0⁺の初期電荷ゼロでは短絡として扱う。" },

    // サ行
    { term: "実効値", reading: "RMS", letter: "さ",
      def: "交流の電力効果が等しい直流値。正弦波では Vrms = Vmax/√2。測定器の電圧・電流は通常この値。" },
    { term: "磁界", reading: "MAGNETIC FIELD", letter: "さ",
      def: "単位長さあたりの起磁力。H = NI/l [A/m]。アンペアの法則 ∮H·dl = NI で計算できる。" },
    { term: "静電容量", reading: "CAPACITANCE", letter: "さ",
      def: "コンデンサに電荷を蓄える能力。Q = CV [F（ファラッド）]。電極の面積・間隔・誘電率で決まる。" },
    { term: "磁束", reading: "MAGNETIC FLUX", letter: "さ",
      def: "磁界の強さと面積の積で表す磁気量。φ = B·A [Wb（ウェーバー）]。電磁誘導の基本量。" },
    { term: "磁束密度", reading: "MAGNETIC FLUX DENSITY", letter: "さ",
      def: "単位面積あたりの磁束。B = φ/A = μH [T（テスラ）]。材料の飽和特性に関係する。" },
    { term: "磁気抵抗", reading: "RELUCTANCE", letter: "さ",
      def: "磁束の流れにくさ。Rm = l/(μA) [A/Wb]。電気回路の抵抗に対応する磁気回路の概念。" },
    { term: "サイリスタ", reading: "THYRISTOR", letter: "さ",
      def: "ゲート信号でターンオンする三端子半導体スイッチ。一旦オンすると電流ゼロまでオフできない。位相制御整流に使用。" },
    { term: "サセプタンス", reading: "SUSCEPTANCE", letter: "さ",
      def: "アドミタンスの虚部。Y = G + jB の B [S]。コンデンサの方向（正）・コイルの方向（負）でサインが変わる。" },
    { term: "重ね合わせの理", reading: "SUPERPOSITION", letter: "さ",
      def: "線形回路で複数電源があるとき、各電源単独で計算した値の代数和が全体の応答になる。電源以外を「短絡（電圧源）」「開放（電流源）」にして計算。" },
    { term: "整流回路", reading: "RECTIFIER CIRCUIT", letter: "さ",
      def: "交流を直流に変換する回路。半波・全波・ブリッジ・三相全波があり、平均値・実効値・脈動率がそれぞれ異なる。" },

    // タ行
    { term: "時定数", reading: "TIME CONSTANT", letter: "た",
      def: "過渡現象の変化速度を決める定数。RC回路では τ = RC、RL回路では τ = L/R [s]。τ秒後に変化量の約63.2%、5τ後に約99%（≈定常）。" },
    { term: "単位法", reading: "PER-UNIT SYSTEM", letter: "た",
      def: "基準値（ベース値）で各量を正規化する表現方法。電力系統の解析でよく使われる。" },
    { term: "テブナンの定理", reading: "THEVENIN", letter: "た",
      def: "任意の線形2端子網は、開放端電圧Vthを持つ電圧源と等価内部抵抗Rthの直列回路に置換できる。Rth計算時は電圧源短絡・電流源開放。" },
    { term: "電界", reading: "ELECTRIC FIELD", letter: "た",
      def: "単位正電荷に働く力の場。E = F/q = V/d [V/m]。静電気の問題の基本量。電位の空間的勾配 E = −dV/dx として定義される。" },
    { term: "電気力線", reading: "ELECTRIC FIELD LINE", letter: "た",
      def: "電界の向きと強さを可視化する仮想の線。正電荷から出て負電荷に入る。電気力線の密度が電界の強さを表す。" },
    { term: "電磁誘導", reading: "ELECTROMAGNETIC INDUCTION", letter: "た",
      def: "磁束の変化によって起電力が生じる現象（ファラデーの法則）。e = −N·dφ/dt。レンツの法則で符号（マイナス）が決まる。" },
    { term: "電位", reading: "ELECTRIC POTENTIAL", letter: "た",
      def: "基準点に対する電気的な位置エネルギー [V]。電圧は2点間の電位差を指す。" },
    { term: "電束密度", reading: "ELECTRIC FLUX DENSITY", letter: "た",
      def: "単位面積あたりの電気変位。D = εE [C/m²]。ガウスの法則で使う量。" },
    { term: "デューティ比", reading: "DUTY RATIO", letter: "た",
      def: "チョッパ等のスイッチング素子で、1周期中にオン状態である時間の比率。降圧チョッパでは Vo = D·Vi。" },
    { term: "伝達関数", reading: "TRANSFER FUNCTION", letter: "た",
      def: "線形システムの入力と出力をラプラス変換し、その比 G(s) = Y(s)/X(s) で表したもの。" },
    { term: "透磁率", reading: "PERMEABILITY", letter: "た",
      def: "磁束の通りやすさを表す材料定数。μ = μ₀μr [H/m]。真空 μ₀ = 4π×10⁻⁷ H/m。鉄心ではμrが数百〜数千。" },
    { term: "ダイオード", reading: "DIODE", letter: "た",
      def: "P型・N型半導体を接合した一方向素子。順バイアスで導通、逆バイアスで遮断（微小な逆飽和電流のみ）。整流・検波に使用。" },

    // ナ行
    { term: "内部抵抗", reading: "INTERNAL RESISTANCE", letter: "な",
      def: "電源や計器が持つ理想的でない抵抗成分。電流が流れると内部抵抗で電圧降下が生じ、端子電圧が起電力より低下する。" },
    { term: "ノートンの定理", reading: "NORTON", letter: "な",
      def: "任意の線形2端子網を、短絡電流Isc・並列内部抵抗Rnの電流源に置換できる。テブナンと相互変換可能：In = Vth/Rth。" },

    // ハ行
    { term: "BH曲線", reading: "BH CURVE", letter: "は",
      def: "磁界強度 H に対する磁束密度 B の関係曲線。磁気飽和とヒステリシスを表す。鉄心設計・トランス効率の基礎。" },
    { term: "ベクトル合成", reading: "PHASOR DIAGRAM", letter: "は",
      def: "フェーザーを2次元平面に描き、振幅と位相の関係を視覚化する図。直角三角形や余弦定理で合成インピーダンスを求める。" },
    { term: "皮相電力", reading: "APPARENT POWER", letter: "は",
      def: "電圧と電流の積。S = VI [VA]。有効電力と無効電力のベクトル和：S = √(P² + Q²)。" },
    { term: "誘電率", reading: "PERMITTIVITY", letter: "は",
      def: "電界の通りやすさを表す材料定数。ε = ε₀εr [F/m]。真空 ε₀ = 8.85×10⁻¹² F/m。" },
    { term: "フェーザー", reading: "PHASOR", letter: "は",
      def: "正弦波交流を複素数で表現したもの。大きさ（実効値または最大値）と位相角を持つ。回路方程式を代数的に解ける。" },
    { term: "複素インピーダンス", reading: "COMPLEX IMPEDANCE", letter: "は",
      def: "Z = R + jX（Rは抵抗成分、Xはリアクタンス成分）。|Z| = √(R² + X²)、偏角が位相差を与える。" },
    { term: "ヒステリシス損", reading: "HYSTERESIS LOSS", letter: "は",
      def: "磁性材料が交流磁界を受けるとき、磁化の向きが反転するたびに発生する熱損失。鉄心損失の一つ。" },
    { term: "PWM制御", reading: "PWM", letter: "は",
      def: "パルス幅変調。スイッチング素子のオン時間を変化させ、平均電圧や正弦波等価出力を作る方式。インバータの基本制御方式。" },
    { term: "百分率インピーダンス", reading: "PERCENT IMPEDANCE", letter: "は",
      def: "定格電流が流れたときの内部インピーダンス電圧降下を定格電圧で割った百分率。短絡電流計算に用いる。" },
    { term: "フレミング左手の法則", reading: "FLEMING LEFT HAND", letter: "は",
      def: "電流が磁界中で受ける力の向きを示す。親指=力F、人差し指=磁界B、中指=電流I。電動機（モーター）に使用。" },
    { term: "フレミング右手の法則", reading: "FLEMING RIGHT HAND", letter: "は",
      def: "導体が磁界中を運動するとき発生する起電力の向きを示す。親指=運動v、人差し指=磁界B、中指=起電力e。発電機に使用。" },
    { term: "ファラデーの法則", reading: "FARADAY LAW", letter: "は",
      def: "コイルを貫く磁束変化が起電力を生む。e = −N·dφ/dt。マイナス符号はレンツの法則（変化を妨げる向き）の表れ。" },
    { term: "半導体", reading: "SEMICONDUCTOR", letter: "は",
      def: "導体と絶縁体の中間の電気伝導性を持つ物質。ケイ素・ゲルマニウムが代表例。不純物添加でN型・P型に分かれる。" },
    { term: "BJT", reading: "BJT", letter: "は",
      def: "バイポーラ接合トランジスタ。NPN/PNP構造でベース電流によりコレクタ電流を制御。電流制御素子。電流増幅率hFE。" },
    { term: "FET", reading: "FET", letter: "は",
      def: "電界効果トランジスタ。ゲート電圧でドレイン電流を制御。電圧制御素子で入力インピーダンスが極めて高い。MOSFET/JFETがある。" },

    // マ行
    { term: "無効電力", reading: "REACTIVE POWER", letter: "ま",
      def: "エネルギーを蓄放するだけで仕事をしない電力。Q = VI·sinφ [var]。コイルは正、コンデンサは負の無効電力を持つ。" },
    { term: "ミルマンの定理", reading: "MILLMAN", letter: "ま",
      def: "並列接続された複数電圧源の合成電圧を求める定理。V = ΣVk/Rk ÷ Σ(1/Rk)。不平衡三相回路の中性点電位計算で使用。" },

    // ヤ行
    { term: "有効電力", reading: "ACTIVE POWER", letter: "や",
      def: "実際に仕事をする電力。P = VI·cosφ = I²R [W]。抵抗で消費される。" },

    // ラ行
    { term: "ローレンツ力", reading: "LORENTZ FORCE", letter: "ら",
      def: "電荷を持つ粒子が電磁界から受ける力。導体では F = BIL·sinθ [N]。電動機の回転力・ホール効果のキャリア偏向の機構。" },
    { term: "リアクタンス", reading: "REACTANCE", letter: "ら",
      def: "交流回路のコイル・コンデンサによる抵抗成分。XL = ωL、XC = 1/(ωC) [Ω]。周波数に依存する。" },
    { term: "力率", reading: "POWER FACTOR", letter: "ら",
      def: "有効電力と皮相電力の比。cosφ = P/S。1に近いほど効率が良い。遅れ（コイル）・進み（コンデンサ）で符号が変わる。" },
    { term: "理想電圧源", reading: "IDEAL VOLTAGE SOURCE", letter: "ら",
      def: "内部抵抗ゼロで、負荷に関わらず一定電圧を供給する電源モデル。テブナン等価変換の出力側に現れる。" },
    { term: "理想電流源", reading: "IDEAL CURRENT SOURCE", letter: "ら",
      def: "内部抵抗無限大で、負荷に関わらず一定電流を供給する電源モデル。ノートン等価変換の出力側に現れる。" },
    { term: "レンツの法則", reading: "LENZ LAW", letter: "ら",
      def: "電磁誘導で発生する誘導電流は、磁束の変化を妨げる向きに流れる。ファラデーの法則の符号（マイナス）の物理的意味。" },
    { term: "RLC回路", reading: "RLC CIRCUIT", letter: "ら",
      def: "抵抗R、コイルL、コンデンサCで構成される交流回路。直列共振では電流最大、並列共振では電流最小。Z = √(R² + (XL−XC)²)。" },
    { term: "RC回路", reading: "RC CIRCUIT", letter: "ら",
      def: "抵抗Rとコンデンサで構成される回路。時定数 τ = RC。充放電過程は指数関数で表される。" },
    { term: "RL回路", reading: "RL CIRCUIT", letter: "ら",
      def: "抵抗RとコイルLで構成される回路。時定数 τ = L/R。電流が指数関数的に立ち上がる/減衰する。" },

    // ワ行・その他
    { term: "ホイートストンブリッジ", reading: "WHEATSTONE BRIDGE", letter: "は",
      def: "4つの抵抗を菱形に配置したブリッジ回路。平衡条件は対辺の積：R₁·R₄ = R₂·R₃。検流計に電流が流れない状態で未知抵抗を測定。" },
    { term: "キルヒホッフの法則", reading: "KIRCHHOFF", letter: "か",
      def: "KCL：節点に流入する電流の代数和は零。KVL：閉路に沿った起電力と電圧降下の代数和は零。回路解析の最も基本的な原理。" },
    { term: "オームの法則", reading: "OHM LAW", letter: "あ",
      def: "電圧V・電流I・抵抗Rの関係 V = IR。直流回路の最も基本的な関係式で、交流ではVもIも複素量・Rもインピーダンス Z に拡張される。" },
    { term: "Y結線", reading: "Y CONNECTION / STAR", letter: "や",
      def: "三相回路の結線方式の一つ。3相の一端を中性点に接続。線電流=相電流、線電圧=√3×相電圧。中性線を引き出せる。" },
    { term: "Δ結線", reading: "DELTA CONNECTION", letter: "た",
      def: "三相回路の結線方式の一つ。3相を環状に接続。線電圧=相電圧、線電流=√3×相電流。中性線がない。" },
    { term: "二電力計法", reading: "TWO WATTMETER METHOD", letter: "な",
      def: "三相3線式の電力測定法。2台の電力計の和 P = W₁ + W₂ で全電力を測定。力率角>60°では一方がマイナスを示すが必ず代数和をとる。" },
    { term: "可動コイル型計器", reading: "MOVING COIL", letter: "か",
      def: "永久磁石の磁界中に置かれたコイルに電流を流して指針を動かす計器。直流専用（交流では指針が振れない）。" },
    { term: "可動鉄片型計器", reading: "MOVING IRON", letter: "か",
      def: "電磁コイルが鉄片を吸引することで動作する計器。電流の向きに依存しないため交流・直流両用で使える。" },
    { term: "倍率器", reading: "MULTIPLIER", letter: "は",
      def: "電圧計の測定範囲を拡大する直列抵抗。電圧計と直列接続して超過電圧を分担する。" },
    { term: "分流器", reading: "SHUNT", letter: "は",
      def: "電流計の測定範囲を拡大する並列抵抗。電流計に並列接続して超過電流を迂回させる。" },
    { term: "オペアンプ", reading: "OP-AMP", letter: "あ",
      def: "高利得差動増幅器。負帰還をかけて使うのが一般的。仮想短絡（V+ = V−）を用いれば反転/非反転増幅などのゲインが容易に導ける。" },
    { term: "仮想接地", reading: "VIRTUAL GROUND", letter: "か",
      def: "オペアンプ反転増幅で、−入力端子が0Vに保たれる現象。仮想短絡の特殊ケース。負帰還のかかったオペアンプ回路でのみ成立。" },
    { term: "空乏層", reading: "DEPLETION LAYER", letter: "か",
      def: "PN接合付近でキャリアが拡散して消滅し、自由電荷がほぼゼロになる領域。順バイアスで縮小、逆バイアスで拡大。" },
    { term: "ツェナーダイオード", reading: "ZENER DIODE", letter: "た",
      def: "逆バイアスで一定電圧（ツェナー電圧）に達すると急激に大電流が流れる特性を利用したダイオード。定電圧源として使用。" },
    { term: "差動増幅", reading: "DIFFERENTIAL AMP", letter: "さ",
      def: "2入力の差を増幅する回路。同相成分（ノイズ等）を除去する能力を持ち、CMRR（同相除去比）で性能評価する。" },
    { term: "ガウスの法則", reading: "GAUSS LAW", letter: "か",
      def: "閉曲面を貫く電束の総和は、その内部の総電荷に等しい。∮D·dS = Q。対称性のある電界計算で威力を発揮。" },
    { term: "ビオ・サバールの法則", reading: "BIOT-SAVART", letter: "は",
      def: "電流素片dlが点Pに作る磁界 dH = (I·dl×r̂)/(4πr²)。直線電流・円形電流の磁界計算の基礎。" },
    { term: "相互インダクタンス", reading: "MUTUAL INDUCTANCE", letter: "さ",
      def: "2つのコイル間の磁気結合の強さ。M = k√(L₁L₂)。和動接続では合成 L₁+L₂+2M、差動接続では L₁+L₂−2M。" },
    { term: "三相電力", reading: "THREE-PHASE POWER", letter: "さ",
      def: "三相回路の総電力。P = √3·VL·IL·cosφ = 3·VP·IP·cosφ。Y/Δで電圧・電流の取り方は異なるが式は等価。" },
  ],

  // 過去問サマリ（交流電力）
  circuitPastQ: [
    { year: "R5", topic: "RL直列回路の有効電力・無効電力分解",         tag: "計算" },
    { year: "R4", topic: "力率改善コンデンサ容量の計算",                  tag: "計算" },
    { year: "R3", topic: "皮相電力・有効電力・無効電力の関係（電力三角形）",tag: "理論+計算" },
    { year: "R2", topic: "複素電力 S = V·I* による有効/無効電力導出",     tag: "計算" },
    { year: "R1", topic: "並列負荷の合成力率と全消費電力",                  tag: "計算" },
    { year: "H30",topic: "RC並列回路の力率・電力計算",                       tag: "計算" },
    { year: "H29",topic: "瞬時電力 p(t) の平均値（=有効電力）",              tag: "理論+計算" },
    { year: "H28",topic: "進相コンデンサ投入時の無効電力変化",                tag: "計算" },
    { year: "H27",topic: "電圧・電流の位相差から力率を求める",                tag: "計算" },
    { year: "H26",topic: "RLC直列回路の電力分解（共振付近）",                tag: "計算" },
  ],

  // 過去問サマリ（演算増幅器）
  opampPastQ: [
    { year: "R5", topic: "反転増幅器の電圧利得 −Rf/Ri",                    tag: "計算" },
    { year: "R4", topic: "非反転増幅器の電圧利得 1+Rf/Ri",                  tag: "計算" },
    { year: "R3", topic: "加算増幅器の出力電圧",                              tag: "計算" },
    { year: "R2", topic: "差動増幅器のCMRR",                                tag: "理論" },
    { year: "R1", topic: "理想オペアンプの特性（無限大入力Z・無限大利得）",   tag: "理論" },
    { year: "H30",topic: "積分回路の出力波形（矩形波→三角波）",               tag: "理論+計算" },
    { year: "H29",topic: "微分回路の動作と出力波形",                          tag: "理論" },
    { year: "H28",topic: "反転増幅器の利得計算（マイナス符号必須）",         tag: "計算" },
    { year: "H27",topic: "コンパレータ動作と出力レベル",                      tag: "理論" },
    { year: "H26",topic: "仮想短絡を用いた回路解析",                          tag: "理論+計算" },
  ],

  // 引っかけパターン全37個
  trapPatterns: [
    {
      num: 1, category: "電磁気",
      trap: "❌ 電子はプラスに引かれるから、電界は−極から+極へ向かう。",
      correct: "✅ 電界の向きは「+電荷が受ける力の向き」=+極（高電位）から−極（低電位）へ。電子は電界の逆向きに動くが、電界の定義は正電荷基準。",
      cite: "（H23問2・H28問1 類出）",
    },
    {
      num: 2, category: "電磁気",
      trap: "❌ コンデンサ2個直列なら合成容量は C/2 になる（抵抗と同じ）。",
      correct: "✅ コンデンサは抵抗と逆転する。直列→逆数の和（小さくなる 1/C = 1/C₁ + 1/C₂）、並列→足し算（C = C₁ + C₂）。直列は極板間が広がる→容量低下と物理で覚える。",
      cite: "（R04上問1・R06下問2 類出）",
    },
    {
      num: 3, category: "電磁気",
      trap: "❌ 電荷Q、電圧Vのコンデンサのエネルギーは W = QV。",
      correct: "✅ 充電中の平均電圧は V/2（0からVへ線形上昇）。W = Q×V/2 = CV²/2。係数1/2を付け忘れる罠。",
      cite: "（H20問3・R05上問1 類出）",
    },
    {
      num: 4, category: "電磁気",
      trap: "❌ 発電機はフレミング左手の法則を使う。",
      correct: "✅ 「何が欲しいか」で手を選ぶ。力Fが欲しい→左手（モーター）、起電力eが欲しい→右手（発電機）。試験中は電動機か発電機かを先に確認。",
      cite: "（H25問4・R05下問3 類出）",
    },
    {
      num: 5, category: "電磁気",
      trap: "❌ 鉄心の磁気抵抗 Rm = l/(μ₀·A)。",
      correct: "✅ 鉄心の透磁率は μ = μ₀·μr。μr は数百〜数千。空隙のみμr=1（空気）。鉄心区間と空隙区間で材料を区別することが必須。",
      cite: "（H29問4・R06上問3 類出）",
    },
    {
      num: 6, category: "電磁気",
      trap: "❌ 2コイルの合成インダクタンスは常に L₁ + L₂ + 2M。",
      correct: "✅ 巻き方（同名端子の向き）で符号が決まる。和動接続→L₁+L₂+2M、差動接続→L₁+L₂−2M。同名端子マーク（•）の向きを確認。",
      cite: "（H24問3・R07上問4 類出）",
    },
    {
      num: 7, category: "直流",
      trap: "❌ 1/Rp = 1/4 + 1/4 = 1/2 だから Rp = 1/2 Ω。",
      correct: "✅ 1/Rp = 1/2 を逆数に戻して Rp = 2 Ω。最後ステップで必ずひっくり返す。2素子なら「積÷和」公式で検算。",
      cite: "（H18問5・R04下問5 類出）",
    },
    {
      num: 8, category: "直流",
      trap: "❌ 等価内部抵抗を求めるとき、電流源を短絡する。",
      correct: "✅ 電圧源→短絡（内部抵抗ゼロ）、電流源→開放（内部インピーダンス無限大）。逆操作をすると等価回路が完全に変わる。",
      cite: "（H27問6・R05上問6 類出）",
    },
    {
      num: 9, category: "直流",
      trap: "❌ RL = Rth のとき電力効率が最大になる。",
      correct: "✅ RL = Rth のときは負荷電力が最大になる条件。電源の半分が内部抵抗で消費されるため効率は50%にすぎない。「電力最大≠効率最大」。",
      cite: "（H22問7・R06下問5 類出）",
    },
    {
      num: 10, category: "交流",
      trap: "❌ 直列RLC回路で Z = R + XL + XC。",
      correct: "✅ RとリアクタンスはベクトルでZを合成。Z = √(R² + (XL−XC)²)。直角三角形の斜辺がZ。スカラー加算は実部同士・虚部同士にしか使えない。",
      cite: "（H19問9・R04上問8 類出）",
    },
    {
      num: 11, category: "交流",
      trap: "❌ コイルは電流が電圧より進む。",
      correct: "✅ ELI the ICEman で整理。L（コイル）はE→I（電流遅れ）、C（コンデンサ）はI→E（電流進み）。「コイルに電圧をかけると電流が追いかける遅れ」と理解。",
      cite: "（H21問8・R05下問9 類出）",
    },
    {
      num: 12, category: "交流",
      trap: "❌ コンセント100Vが最大値だ。",
      correct: "✅ 100Vは実効値。最大値は 100√2 ≈ 141V。絶縁設計は最大値を使う。実効値は「等しい仕事量をする直流値」（正弦波で Vmax/√2）。",
      cite: "（H18問8・R06上問8 類出）",
    },
    {
      num: 13, category: "三相",
      trap: "❌ Y結線でも線電流 = √3 × 相電流になる。",
      correct: "✅ Y結線は線電流=相電流（√3なし）、線電圧=√3×相電圧。Δ結線は線電圧=相電圧（√3なし）、線電流=√3×相電流。「Y→電圧に√3、Δ→電流に√3」と整理。",
      cite: "（H20問12・R05上問13 類出）",
    },
    {
      num: 14, category: "三相",
      trap: "❌ 三相電力は単相電力 P₁ = VP·IP·cosφ の3倍だから P = 3VL·IL·cosφ。",
      correct: "✅ Y結線では VP = VL/√3 なので代入すると P = 3×(VL/√3)×IL·cosφ = √3·VL·IL·cosφ。3/√3 = √3 になる。3VL·IL·cosφ は誤り。",
      cite: "（H23問13・R07上問11 類出）",
    },
    {
      num: 15, category: "電子",
      trap: "❌ N型はNegativeの略だから、物質全体が負電荷を持っている。",
      correct: "✅ N型のNは「多数キャリアが電子（Negative）」を意味するだけ。リン原子は+5価の核と4個の共有結合で安定し余剰電子1個放出後は正イオン化する。物質全体は中性。",
      cite: "（H24問14・R06上問13 類出）",
    },
    {
      num: 16, category: "電子",
      trap: "❌ ダイオードに逆バイアスをかけると電流はゼロになる。",
      correct: "✅ 逆バイアスでも微小な逆飽和電流 Is が流れる。温度依存性が高く、温度上昇で急増する。ツェナー降伏電圧で急激に大電流（ツェナーダイオードはこれを利用）。",
      cite: "（H26問14・R05下問13 類出）",
    },
    {
      num: 17, category: "電子",
      trap: "❌ 反転増幅回路のゲインは Av = Rf/Ri。",
      correct: "✅ 反転増幅は出力が入力と逆位相になるため Av = −Rf/Ri。ゲイン絶対値を問うなら |Av| = Rf/Ri でよいが、出力電圧を求めるならマイナス符号が必須。",
      cite: "（H28問18・R06下問17 類出）",
    },
    {
      num: 18, category: "過渡",
      trap: "❌ コンデンサは電荷を蓄えるから、スイッチ直後は電流が流れない→開放として扱う。",
      correct: "✅ 初期電荷ゼロのコンデンサは t=0⁺ で短絡（電圧=0を維持しようとするため電流が最大値で流れ始める）。定常状態では充電完了し電流ゼロ→開放。直後と定常後で扱いが逆転する。",
      cite: "（H25問10・R04上問10 類出）",
    },
    {
      num: 19, category: "過渡",
      trap: "❌ 時定数τ後に回路は定常状態になる。",
      correct: "✅ τ後には定常値の約63%（1−1/e ≈ 63.2%）に達するだけ。5τ後にようやく99%（≈定常値）。「τ=100%」は誤り。i(τ) = I∞(1 − e⁻¹)で計算する。",
      cite: "（H22問10・R05上問10 類出）",
    },
    {
      num: 20, category: "計測",
      trap: "❌ 可動コイル型は電流の大きさに反応するから、交流でも使える。",
      correct: "✅ 可動コイル型は直流専用。永久磁石の磁界と電流の向きで力が発生する仕組み。交流では電流の向きが毎サイクル反転し、力も反転→指針が振れずゼロ。交流測定は可動鉄片型・整流型を使う。",
      cite: "（H19問15・R06下問14 類出）",
    },
    {
      num: 21, category: "電磁気",
      trap: "❌ 磁束密度B=1.2[T]、透磁率μ₀=4π×10⁻⁷[H/m]のとき、磁界H=1.2[A/m]である。",
      correct: "✅ BとHは別の物理量で B=μH（μ=μ₀μr）で結びつく。Bは「磁束の密度」、Hは「磁界の強さ」。真空・空気中ならμr=1でB=μ₀H、磁性体ではμrが数百〜数千になりBとHの比が変わる。比透磁率の記載があれば必ずμ=μ₀μrを使う。",
      cite: "（H21問3・R01上問4 類出）",
    },
    {
      num: 22, category: "電磁気",
      trap: "❌ 電荷Q[C]を持つ平行板コンデンサで、極板間の電界がE[V/m]なら、一方の極板に働く力はF=QE[N]である。",
      correct: "✅ F=QEは「外部電界E中の点電荷Qに働く力」の式で、コンデンサ極板には直接適用できない。一方の極板が感じるのは「相手極板が作る電界」だけ。面電荷密度σ=Q/Sとすると一枚の極板が作る電界はσ/(2ε₀)で、力は F = Q×σ/(2ε₀) = σ²S/(2ε₀)。全電界Eに対しては F=QE/2（係数1/2）が本質。",
      cite: "（H25問5・R03上問2 類出）",
    },
    {
      num: 23, category: "電磁気",
      trap: "❌ 電位V[V]が大きい点ほど電界E[V/m]も強い。",
      correct: "✅ 電界は電位の「空間的な変化率（勾配）」で E = −dV/dx。電位の絶対値ではなく「どれだけ急激に変化しているか」が電界の強さを決める。等電位面上では電位変化ゼロなのでその方向に電界はない（電界は等電位面に常に垂直）。",
      cite: "（H19問2・R05上問1 類出）",
    },
    {
      num: 24, category: "直流",
      trap: "❌ 節点Aに流れ込む電流をI₁と設定したらI₁=−2 A。負の値が出たので設定が間違いと判断しやり直した。",
      correct: "✅ KCLで電流方向の仮定は計算上の便宜であり、解が負になることは「仮定と逆向きに実際は流れている」ことを意味するだけで誤りではない。I₁=−2 Aは「A点から流れ出す方向に2 A」の正しい物理的意味。そのまま他の方程式に代入して連立を解けばよい。やり直すと別の符号ミスを誘発する。",
      cite: "（H22問2・R03上問2 類出）",
    },
    {
      num: 25, category: "直流",
      trap: "❌ 起電力E=12 Vの電池に外部抵抗R=4 Ωを接続。外部抵抗の電圧は12 Vだから電流はI=12/4=3 Aである。",
      correct: "✅ 実際の電池には内部抵抗rが直列に存在する。電流が流れると内部抵抗で電圧降下I·rが生じ、端子電圧は V = E − I·r。「起電力=端子電圧」が成立するのは電流ゼロの開放状態のみ。問題文に内部抵抗が与えられていれば必ず回路に組み込む。",
      cite: "（H19問3・R01問3 類出）",
    },
    {
      num: 26, category: "直流",
      trap: "❌ ホイートストンブリッジで上辺左R₁・上辺右R₂、下辺左R₃・下辺右R₄の場合、平衡条件はR₁·R₂=R₃·R₄である。",
      correct: "✅ ブリッジ平衡条件は「向かい合う対辺の積が等しい」で、正しくは R₁·R₄ = R₂·R₃（上左×下右 = 上右×下左）。検流計に電流が流れない条件 R₁/R₂ = R₃/R₄ から導出される。隣接辺ではなく対角辺の積であることを回路図で確認。",
      cite: "（H25問4・R05上問4 類出）",
    },
    {
      num: 27, category: "交流",
      trap: "❌ RLC直列回路の共振周波数ではコイルとコンデンサのリアクタンスが打ち消し合うのだから、回路全体のインピーダンスが最大になる。",
      correct: "✅ 直列共振では ωL = 1/(ωC) のとき誘導性と容量性リアクタンスが完全に相殺。Z = √(R²+(ωL−1/ωC)²) の虚部がゼロになり Z = R（純抵抗のみ）。これがインピーダンス最小値で最大電流が流れる。「共振=打ち消し=最小Z=最大I」という因果。並列共振では逆（最大Z）になるため混同注意。",
      cite: "（H24問9・R02下問9 類出）",
    },
    {
      num: 28, category: "交流",
      trap: "❌ RLC並列回路の共振周波数では、直列共振と同じくインピーダンスが最小になり電源から最大電流が流れる。",
      correct: "✅ 並列回路ではアドミタンス Y = G + j(ωC − 1/(ωL)) で考える。共振時は虚部ゼロで Y = G（最小アドミタンス）→ Z = 1/Y で最大インピーダンス、電源からの電流は最小。ただしL・C間では大きな循環電流が流れる（並列共振の本質）。",
      cite: "（H26問10・R04上問10 類出）",
    },
    {
      num: 29, category: "交流",
      trap: "❌ 皮相電力S、有効電力P、無効電力Qの関係はS=P+Qであり、Qは常に正の値をとる。",
      correct: "✅ 三者の関係はスカラー加算でなく S² = P² + Q²（電力の三角形）。またQの符号は負荷で変わる。誘導性負荷（電流遅れ）でQ>0、容量性負荷（電流進み）でQ<0。力率cosφ = P/S。Qの符号を誤ると力率改善の補償方向が逆になる致命ミス。",
      cite: "（H21問11・R03下問11 類出）",
    },
    {
      num: 30, category: "三相",
      trap: "❌ 二電力計法でW₁=800 W、W₂=−200 Wだった。三相電力はW₁−W₂=1000 Wだ。",
      correct: "✅ 二電力計法の三相全電力は P = W₁ + W₂（常に代数和）。W₂がマイナスは力率角>60°で物理的に起こりうる現象で、符号ごと足す。引き算に変えてはならない。P = 800 + (−200) = 600 W が正答。",
      cite: "（H24問9・R02上問9 類出）",
    },
    {
      num: 31, category: "三相",
      trap: "❌ 三相3線式の不平衡回路でも、各相の相電圧は線間電圧を√3で割れば求まる。",
      correct: "✅ 相電圧=線間電圧÷√3 が成立するのは中性点が固定されている場合（中性線あり4線式、または平衡負荷）のみ。中性線なしの3線式不平衡回路は各相電流が等しくなく中性点電位がシフトする。ミルマンの定理で中性点電位 V_N を求め、各相電圧=線間電圧−V_N で計算する。",
      cite: "（H27問8・R04上問9 類出）",
    },
    {
      num: 32, category: "電子",
      trap: "❌ MOSFETはゲートに電圧をかけて動作するのだから、ゲート電流が流れて入力インピーダンスはバイポーラトランジスタと同程度だ。",
      correct: "✅ MOSFETのゲートは金属酸化膜（SiO₂）で基板と絶縁されており、定常状態ではゲート電流はほぼゼロ（漏れ電流のみ数pA〜nA）。これが入力インピーダンス10⁸Ω以上の理由。バイポーラのベース電流（hFEで規定される実電流）とは物理機構が根本的に異なる「電圧制御素子」が高インピーダンスの原因。",
      cite: "（H22問14・R03上問14 類出）",
    },
    {
      num: 33, category: "電子",
      trap: "❌ 順バイアスをかけると電流が流れやすくなるので空乏層が広がり、逆バイアスでは電流が止まるので空乏層が狭まる。",
      correct: "✅ 順バイアスでは外部電圧がpn接合の内蔵電位（ビルトインポテンシャル）を打ち消す方向に働き、空乏層は縮小する。逆バイアスでは内蔵電位を強める方向に働き、空乏層は拡大する。電流の流れやすさと空乏層の広さは逆の関係。逆バイアスで広がった空乏層がコンデンサとして機能するのがバラクタダイオード。",
      cite: "（H25問15・R01問15 類出）",
    },
    {
      num: 34, category: "過渡",
      trap: "❌ RL直列回路でスイッチを閉じた直後（t=0⁺）、インダクタは抵抗がないので電流はすぐに流れ始める。",
      correct: "✅ インダクタは電流の変化を妨げる素子（v = L·di/dt）。t=0⁺では電流をゼロのまま維持しようとするため開放として扱う。コンデンサ（t=0⁺は短絡）と逆の性質で混同が頻出。定常状態（t→∞）では電流一定で v=0 →短絡。直後と定常後の扱いがコンデンサと完全に逆になる。",
      cite: "（H22問3・R03上問3 類出）",
    },
    {
      num: 35, category: "過渡",
      trap: "❌ RL直列回路の時定数はτ=CR、RC直列回路の時定数はτ=L/Rである。",
      correct: "✅ 時定数の次元は「秒[s]」でなければならない。τ=L/Rは[H]/[Ω]=[s]、τ=CRは[F]·[Ω]=[s]とどちらも次元が合うことを確認。RL回路の微分方程式 L·di/dt + R·i = 0 を解くと指数係数R/L→時定数 L/R。RC回路ではCR·dv/dt + v = 0 を解くと係数1/CR→時定数 CR。単位チェックの習慣が混同を防ぐ。",
      cite: "（H25問4・R01問3 類出）",
    },
    {
      num: 36, category: "計測",
      trap: "❌ 精度の高い電流計は内部抵抗が大きい。",
      correct: "✅ 電流計は測定対象に直列に挿入する。内部抵抗が大きいほど回路全体の抵抗が変化し、本来の電流値が変わってしまう（誤差増大）。理想電流計の内部抵抗は0Ω。電圧計は並列接続のため内部抵抗が大きいほど誤差が小さくなる（理想電圧計は∞Ω）。「直列→低抵抗」「並列→高抵抗」と接続目的から導ける。",
      cite: "（H19問7・R04上問8 類出）",
    },
    {
      num: 37, category: "計測",
      trap: "❌ 測定レンジを広げるため、電圧計に分流器（並列抵抗）を付ける。",
      correct: "✅ 電圧計のフルスケール超過電圧を測るには超過分を別の抵抗で「分担」させる必要があり、電圧は直列素子で分圧されるので直列に抵抗（倍率器）を追加する。電流計の場合は超過電流を「迂回」させる必要があり並列に抵抗（分流器）を追加する。目的（電圧を分担／電流を迂回）から接続形式が決まる。",
      cite: "（H23問8・R02問8 類出）",
    },
  ],
};
